-- ============================================================
-- HEALTHCARE DATA WAREHOUSE
-- ============================================================

-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS HEALTHCARE_DW;

-- USE DATABASE
USE DATABASE HEALTHCARE_DW;

-- CRAETE SCHEMAS
CREATE SCHEMA  IF NOT EXISTS HEALTHCARE_DW.RAW_SCHEMA;
CREATE SCHEMA  IF NOT EXISTS HEALTHCARE_DW.STAGING_SCHEMA;
CREATE SCHEMA  IF NOT EXISTS HEALTHCARE_DW.ANALYTICS_SCHEMA;

-- VERIFY
SHOW DATABASES;
SHOW SCHEMAS;
