
-- TIME TRAVEL
SELECT *
FROM ANALYTICS_SCHEMA.dim_patients
AT (OFFSET => -60*5);

-- RESTORING TABLE
CREATE TABLE ANALYTICS_SCHEMA.dim_patients_backup
AS 
SELECT *
FROM ANALYTICS_SCHEMA.dim_patients
AT (OFFSET => -60*5);

SELECT * FROM ANALYTICS_SCHEMA.dim_patients_backup;


-- ZERO-COPY CLONING
CREATE TABLE ANALYTICS_SCHEMA.dim_patients_clone
CLONE ANALYTICS_SCHEMA.dim_patients;

UPDATE ANALYTICS_SCHEMA.dim_patients_clone
SET city = 'GURGAON'
WHERE city = 'GURUGRAM';

SELECT *
FROM ANALYTICS_SCHEMA.dim_patients_clone;


-- RBAC - ROLE BASED ACCESS CONTROL
-- CREATE ROLE
CREATE ROLE IF NOT EXISTS HEALTHCARE_ANALYST;

-- GRANT DATABASE USAGE
GRANT USAGE
ON DATABASE HEALTHCARE_DW
TO ROLE HEALTHCARE_ANALYST;

-- GRANT SCHEMA USAGE
GRANT USAGE
ON SCHEMA HEALTHCARE_DW.ANALYTICS_SCHEMA
TO ROLE HEALTHCARE_ANALYST;

-- GRANT READ ACCCESS
GRANT SELECT
ON ALL TABLES IN SCHEMA HEALTHCARE_DW.ANALYTICS_SCHEMA
TO ROLE HEALTHCARE_ANALYST;


SHOW GRANTS TO ROLE HEALTHCARE_ANALYST;
